### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by Anant7393** [DSC-JSS-NOIDA/QuickLearn#44] opened 2021-10-06 17:59 UTC

**Comment by shray-jayn** [comment] 2021-10-07 09:51
I have added a Favicon 

![favicon](https://user-images.githubusercontent.com/76147471/136361661-d31a8161-d287-4ce2-a89f-3e558223eb06.png)


pls, review and merge pr #54.
Thanks in advance.

**Comment by Ashish4321-hub** [comment] 2022-02-25 17:46
@Anant7393  I want to add favicon .I have lot of favicon.
pls assign me this issue.

**Comment by Ashish4321-hub** [comment] 2022-02-25 17:54
@Anant7393  I want to add favicon on this website.
please assign me this issue.

**Comment by AnweshaRoses** [comment] 2022-02-28 03:49
I am a GSSOC participant, if the issue is still not solved I would love working on it

**Comment by ManaliPawar** [comment] 2022-02-28 05:45
i would like to work on this issue,can you please assign me? I am a GSSOC participant

**Comment by UdAyAn123** [comment] 2022-03-01 04:16
I am looking forward to this issue

**Comment by ritikaaaa177** [comment] 2022-03-01 05:04
i ama gssoc prticipant can you please assign me this issue ?

**Comment by Sanghu01** [comment] 2022-03-01 07:11
I want to work on this issue under the gssoc 22. i can do it as soon as possible... plz assign me this.

**Comment by Sanghu01** [comment] 2022-03-03 15:19
I WANT TO WORK ON THIS ISSUE UNDER GSSOC'22.

**Comment by saidhanya18** [comment] 2022-03-08 03:11
could you please this issue to me

**Comment by Keyurchaniyara** [comment] 2022-03-09 05:37
Hello 

I am a GSSoC22 contributor. I would love to work on this issue and as soon as I make fevicon for this issue. Please do assign this to me.

ThankYou:)

**Comment by prachi1211** [comment] 2022-03-09 05:38
Hello
I am a Gssoc'22 Contributor. Kindly assign me this task.
Thank You.

**Comment by YatreeLadani** [comment] 2022-03-09 05:53
I'm an GSSOc'22 Contributor, please Assign me this task.

**Comment by AMAN123956** [comment] 2022-03-09 08:05
For now current favicon is good enough so I am closing this issue u all can work on other issues that are there

**Closed** 2022-03-09 08:05 UTC
